networks:
  pg-network:
    external: true
    
services:
  pgdatabase:
    image: postgres:13
    container_name: pg_database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -h localhost -d ny_taxi"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      pgdatabase:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pg-network
